### ISSUE TITLE
Logging and Monitoring Kubernetes cluster

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#10]
- Using in-built Graphana + Prometheus, explained at http://blog.arungupta.me/kubernetes-monitoring-heapster-influxdb-grafana/
- EFK (Elasticsearch + Fluentd + Kibana)
- Fluentd -> CloudWatch logs and ElasticSearch
- Statsd
- Which partners should be highlighted?

**Comment by omarlari** [comment]
assign to @omalari

**Comment by omarlari** [comment]
pulled and merged.
