### ISSUE TITLE
Calico network policy is not restricting pod access

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#106]
https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/calico#create-default-network-policy is passing where as the text expects this to fail.

Either way, using the command as is fails:

```
/ # wget -S http://http-echo.ns-1.svc.cluster.local/test --post-data '{"message":"hello"}'
Connecting to http-echo.ns-1.svc.cluster.local (100.64.161.56:80)
  HTTP/1.1 200 OK
  X-Powered-By: Express
  Content-Type: application/json; charset=utf-8
  Content-Length: 535
  ETag: W/"217-L0a4mh327enPVmj7E/9mJHFg4kw"
  Date: Thu, 26 Oct 2017 02:12:48 GMT
  Connection: close
  
wget: can't open 'test': File exists
```

Had to change the URL from `http://http-echo.ns-1.svc.cluster.local/test` to `http://http-echo.ns-1.svc.cluster.local/test2`.

Additionally, `test3` URL at https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/calico#create-network-policy-with-a-rule fails as well.

**Comment by boardthatpowder** [comment]
Fixed the wget command to race overwriting local files, but could not reproduce the failing calico issues.  PR>  https://github.com/arun-gupta/kubernetes-aws-workshop/pull/116

**Comment by arun-gupta** [comment]
FYI @wombat

**Comment by arun-gupta** [comment]
Fixed with https://github.com/arun-gupta/kubernetes-aws-workshop/pull/184
