### ISSUE TITLE
S3 bucket to store Kubernetes config

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#107]
aws s3api create-bucket --bucket kubernetes-aws-io

gives
An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

You should advise users to suffix the bucket.

**Comment by cloudymind** [comment]
Also fixed in upcoming PR
