### ISSUE TITLE
Region mismatch between labs

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#109]
pre-requisites asks to set region to export AWS_DEFAULT_REGION=eu-central-1

while kops tutorial uses us-east-1

kops create cluster \
  --name cluster.kubernetes-aws.io \
  --zones us-east-1d,us-east-1e \
  --state s3://kubernetes-aws-io \
  --yes

Is this intentional?

**Comment by cloudymind** [comment]
This is fixed. I am going through the cluster install steps, the PR just hasn't been added yet.

**Comment by arun-gupta** [comment]
Fixed in https://github.com/arun-gupta/kubernetes-aws-workshop/pull/112
