### ISSUE TITLE
Service mesh integration with k8s

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#11]
Show how service mesh integrate with k8s on AWS. The couple of possibilities:

- Linkerd
- Istio/Envoy

**Comment by omarlari** [comment]
assign to @omarlari

**Comment by dalbhanj** [comment]
assign this to dalbhanj@, spoke to omarlari and he is okay with moving this to me

**Comment by MCLDG** [comment]
PR #92 adds Istio. We could probably do with one or two other linkerd examples before we close this issue. Aim is to show how useful the mesh is for enterprises running microservices.

**Comment by MCLDG** [comment]
PR #94 means this issue can be closed
