### ISSUE TITLE
parallel job not created

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#111]
kubectl apply -f templates/job-parallel.yaml

The Job "wait" is invalid: spec.completions: Invalid value: 6: field is immutable

**Comment by dalbhanj** [comment]
should be fixed in https://github.com/arun-gupta/kubernetes-aws-workshop/pull/115

You need to to delete the job before running parallel jobs
 $ kubectl delete -f templates/job.yaml

**Comment by arun-gupta** [comment]
#115 merged and closing the issue
