### ISSUE TITLE
cron job issues

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#113]
kubectl create -f template/cronjob.yaml --validate=false

folder is templates.

**Comment by asifamz** [comment]
further: 
kubectl create -f templates/cronjob.yaml --validate=false
error: unable to recognize "templates/cronjob.yaml": no matches for batch/, Kind=CronJob

**Comment by arun-gupta** [comment]
Did you follow the pre-reqs as defined at https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/developer-concepts#pre-requisites-1?

**Comment by cloudymind** [comment]
I hit this error as well. Looks to be a known issue:
https://github.com/kubernetes/website/issues/2325

**Comment by arun-gupta** [comment]
@cloudymind what version of Kubernetes?

1.7.x is `v2alpha1` and 1.8 is `batch/v1beta1`

**Comment by cloudymind** [comment]
Yeah, I was 1.7.4 so after I performed a rolling update to apiversion v2alpha1 the cron job was implemented correctly.

**Comment by arun-gupta** [comment]
OK, thanks for confirming, will close the issue.

@asifamz feel free to reopen the issue if you are still experiencing it.
