### ISSUE TITLE
Logging 

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#123]
1. Delete cluster needs to be detailed.

2. kubectl create -f ./templates/fluentd-role.yaml
Error from server (AlreadyExists): error when creating "./templates/fluentd-role.yaml": clusterroles.rbac.authorization.k8s.io "fluentd-read" already exists

kubectl create -f ./templates/fluentd-role-binding.yaml
Error from server (AlreadyExists): error when creating "./templates/fluentd-role-binding.yaml": clusterrolebindings.rbac.authorization.k8s.io "fluentd-read" already exists

i followed the steps in the tutorial and get this error but could complete the tutorial.

**Comment by asifamz** [comment]
Also, you should put relevant screenshot of logs visualization, cant assume people to know kibana as they will skip over it.

**Comment by arun-gupta** [comment]
The following errors are occurring because the resources were created once, and then attempted to create again:

```
kubectl create -f ./templates/fluentd-role.yaml
Error from server (AlreadyExists): error when creating "./templates/fluentd-role.yaml": clusterroles.rbac.authorization.k8s.io "fluentd-read" already exists

kubectl create -f ./templates/fluentd-role-binding.yaml
Error from server (AlreadyExists): error when creating "./templates/fluentd-role-binding.yaml": clusterrolebindings.rbac.authorization.k8s.io "fluentd-read" already exists
```
