### ISSUE TITLE
Upgrading K8s chapter

### ISSUE THREAD

**Issue by asifamz** [arun-gupta/kubernetes-aws-workshop#124]
1. cluster install link broken
2. will this work with the cluster we set up using gossip , or do we need external DNS.
3. is this tuorial advising to create a new cluster.
4. how do we do blue-green, instructions are light?
5. can we explain the steps to achieve blue green

**Comment by arun-gupta** [comment]
Instructions for rolling update are updated with more details.

Blue/green will be covered in https://github.com/arun-gupta/kubernetes-aws-workshop/issues/38
