### ISSUE TITLE
Prerequisites for aws configure miss availability zone information

### ISSUE THREAD

**Issue by bpasson** [arun-gupta/kubernetes-aws-workshop#146]
The prerequisites do not mention to set availability zone to eu-central-1 during *aws configure* step. Further on in the prerequisites you are asked to check the following:

echo $AWS_AVAILABILITY_ZONES
eu-central-1a,eu-central-1b,eu-central-1c

**Comment by arun-gupta** [comment]
Already integrated with https://github.com/arun-gupta/kubernetes-aws-workshop/pull/145
