### ISSUE TITLE
If you haven't complete the signup process...

### ISSUE THREAD

**Issue by EelcoMeuter** [arun-gupta/kubernetes-aws-workshop#148]
In rare occasions you could fail the complete the sign up process.

When you try to follow the Kubernetes Workshop Prereqs ->AWS Availability Zones you may run into the following error:

```
An error occurred (OptInRequired) when calling the DescribeAvailabilityZones operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe
```

If so, please go to AWS console -> EC2 and follow the missing steps that are presented on that page.

**Comment by arun-gupta** [comment]
@EelcoMeuter do you want to send a PR?
