### ISSUE TITLE
Configuration and Secrets management

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#15]
Show how secrets can be managed on Kubernetes: https://kubernetes.io/docs/concepts/configuration/secret/

- `kubectl create secret`
- Using configuration file
- Using in an application
- Using `ConfigMap`

Other use cases explained at https://kubernetes.io/docs/concepts/configuration/secret/.

**Comment by arun-gupta** [comment]
Added https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/config-secrets

**Comment by MCLDG** [comment]
Should we show integration with AWS, and integrate secrets from AWS Parameter Store? Though it does look as though this won't be in EKS v1.

**Comment by arun-gupta** [comment]
@MCLDG I think that makes perfect sense. Do you want to send a PR?
