### ISSUE TITLE
ALB Ingress Controller

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#16]
https://github.com/coreos/alb-ingress-controller

**Comment by cloudymind** [comment]
assign to @cloudymind

**Comment by Raffo** [comment]
You can also consider https://github.com/zalando-incubator/kube-ingress-aws-controller that we use in production at Zalando.

**Comment by arun-gupta** [comment]
@Raffo do you have any examples of how blue/green is done using this controller?

**Comment by Raffo** [comment]
We don't do it at the ALB level, we have an ingress controller on each node that is responsible for that. A valid alternative is doing blue/green by having a kubernetes service pointing to the blue deployment and green deployment and scaling manually the pods in the two deployments. In this way, the ALB is only responsible to route all traffic to the nodes.

**Comment by arun-gupta** [comment]
@Raffo is this something similar to https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/app-update#canary-deployment?

**Comment by Raffo** [comment]
Yes for the second part of my answer. 

For the scenario in which we have an ingress controller running as a DaemonSet, we have **both** a blue and green service and deployment pair: it's the ingress controller that makes the decision on which service to route.

**Comment by arun-gupta** [comment]
@Raffo what criteria is used by the ingress controller for the decision?

**Comment by Raffo** [comment]
Weight, in a similar fashion to what is described in this issue: https://github.com/zalando/skipper/issues/324

**Comment by arun-gupta** [comment]
@Raffo Core OS is ALB ingress controller. The one recommended by you works with Skipper, not with ALB, right?

**Comment by Raffo** [comment]
Well no, it creates an ALB which we use with a single target group: all the worker nodes of the cluster are the target group and they run Skipper (as DaemonSet = 1 pod per node).

**Comment by MCLDG** [comment]
PR#247 should resolve this.
