### ISSUE TITLE
Target port not specified on service expose

### ISSUE THREAD

**Issue by JorgeAlmeida** [arun-gupta/kubernetes-aws-workshop#162]
In the Updating applications & Canary deployment lab we get an empty response from the server.

This:
`kubectl expose deployment/app-recreate --port=80 --name=app-recreate --type=LoadBalancer`

Should be this:
`kubectl expose deployment/app-recreate --port=80 --target-port=8080 --name=app-recreate --type=LoadBalancer`

**Comment by arun-gupta** [comment]
Waiting for the PR
