### ISSUE TITLE
`kube2iam` example's `aws ec2 describe-instances` call assumes an `us-east-1` region

### ISSUE THREAD

**Issue by dnedev** [arun-gupta/kubernetes-aws-workshop#167]
In the [example for `kube2iam`](https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/roles#iam-role-for-worker), the call to obtain the IAM Role ARN assigned to the worker nodes, namely
```
kubectl get no \
  --selector=kubernetes.io/role==node \
  -o jsonpath='{.items[0].spec.externalID}' | \
  xargs aws ec2 describe-instances \
  --instance-id \
  --region us-east-1 \
  --query 'Reservations[*].Instances[*].IamInstanceProfile.Arn' | \
  sed -e 's/instance-profile/role/g'
```
assumes the region is `us-east-1`. As a result, if running in a different region, the AWS CLI call will fail, as the instance will not be found in the `us-east-1` region. 
Since we set a default region, usually, in the initial setup using `aws configure`, we can omit the `  --region us-east-1 \` line.

**Comment by arun-gupta** [comment]
@dnedev send a PR?

**Comment by dnedev** [comment]
Coming up ;)
