### ISSUE TITLE
Kubernetes Getting Started

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#17]
- Download and run minikube: https://github.com/kubernetes/minikube
- Get familiar with `kubectl`
- Run a simple pod

**Comment by arun-gupta** [comment]
Something like:

. Create pod: `kubectl run nginx --image=nginx`
. Check status: `kubectl get -w pods`

**Comment by omarlari** [comment]
assign to @omarlari

**Comment by omarlari** [comment]
Pulled and merged
