### ISSUE TITLE
Errors during kops create cluster

### ISSUE THREAD

**Issue by FreekDB** [arun-gupta/kubernetes-aws-workshop#172]
freek@freek-vb-u1604:~/freek/AwsWorkshop$ kops create cluster --name example.cluster.k8s.local --zones $AWS_AVAILABILITY_ZONES --yesI1101 17:45:59.101286   10742 create_cluster.go:659] Inferred --cloud=aws from zone "eu-west-1a"
I1101 17:45:59.101775   10742 create_cluster.go:845] Using SSH public key: /home/freek/.ssh/id_rsa.pub
I1101 17:45:59.968288   10742 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet eu-west-1a
I1101 17:45:59.968395   10742 subnets.go:183] Assigned CIDR 172.20.64.0/19 to subnet eu-west-1b
I1101 17:45:59.968430   10742 subnets.go:183] Assigned CIDR 172.20.96.0/19 to subnet eu-west-1c
I1101 17:46:03.860011   10742 apply_cluster.go:420] Gossip DNS: skipping DNS validation
I1101 17:46:04.641727   10742 executor.go:91] Tasks: 0 done / 71 total; 32 can run
I1101 17:46:05.843902   10742 vfs_castore.go:422] Issuing new certificate: "kube-controller-manager"
I1101 17:46:06.188515   10742 vfs_castore.go:422] Issuing new certificate: "kubelet"
I1101 17:46:06.210547   10742 vfs_castore.go:422] Issuing new certificate: "kops"
I1101 17:46:06.270088   10742 vfs_castore.go:422] Issuing new certificate: "kubecfg"
I1101 17:46:06.382996   10742 vfs_castore.go:422] Issuing new certificate: "kube-proxy"
I1101 17:46:06.390068   10742 vfs_castore.go:422] Issuing new certificate: "kube-scheduler"
I1101 17:46:09.405837   10742 executor.go:91] Tasks: 32 done / 71 total; 15 can run
I1101 17:46:10.060515   10742 executor.go:91] Tasks: 47 done / 71 total; 20 can run
I1101 17:46:11.174802   10742 launchconfiguration.go:327] waiting for IAM instance profile "masters.example.cluster.k8s.local" to be ready
I1101 17:46:11.189152   10742 launchconfiguration.go:327] waiting for IAM instance profile "nodes.example.cluster.k8s.local" to be ready
I1101 17:46:21.568032   10742 executor.go:91] Tasks: 67 done / 71 total; 3 can run
I1101 17:46:22.460514   10742 vfs_castore.go:422] Issuing new certificate: "master"
I1101 17:46:23.011523   10742 executor.go:91] Tasks: 70 done / 71 total; 1 can run
I1101 17:46:23.257910   10742 executor.go:91] Tasks: 71 done / 71 total; 0 can run
I1101 17:46:23.268220   10742 kubectl.go:133] error running kubectl config view --output json
I1101 17:46:23.268276   10742 kubectl.go:134] 
I1101 17:46:23.268290   10742 kubectl.go:135] 
W1101 17:46:23.268498   10742 update_cluster.go:235] error reading kubecfg: error getting config from kubectl: error running kubectl: fork/exec /usr/local/bin/kubectl: exec format error
I1101 17:46:23.495635   10742 update_cluster.go:247] Exporting kubecfg for cluster
Kops has set your kubectl context to example.cluster.k8s.local

Cluster changes have been applied to the cloud.

Changes may require instances to restart: kops rolling-update cluster

freek@freek-vb-u1604:~/freek/AwsWorkshop$ echo $AWS_AVAILABILITY_ZONES
eu-west-1a,eu-west-1b,eu-west-1c

**Comment by wombat** [comment]
@FreekDB Did you have the linux version of kubectl or the mac version? There was a bug in the documentation where accidentally the mac version was downloaded.

**Comment by FreekDB** [comment]
@wombat That seems to be the cause of the problem, that is a good catch! I checked the version of the web page that I used to install kubectl and it used the darwin/macOS one (from https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/getting-started):
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
chmod +x kubectl && sudo mv kubectl /usr/local/bin/

The command that I used to install kubectl (from the history; **bold** added by me):
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/**darwin**/amd64/kubectl

Thank you very much for resolving the issue! I will retry creating a cluster soon (and after downloading the right version of kubectl).

**Comment by wombat** [comment]
@FreekDB cool - let me know it that solved the issue so we can close this ticket

**Comment by FreekDB** [comment]
As expected, creating the cluster works fine after downloading the right version of kubectl:

freek@freek-vb-u1604:~/freek/AwsWorkshop$ kops create cluster --name example.cluster.k8s.local --zones $AWS_AVAILABILITY_ZONES --yes
I1104 01:07:13.568599   18019 create_cluster.go:659] Inferred --cloud=aws from zone "eu-west-1a"
I1104 01:07:13.573564   18019 create_cluster.go:845] Using SSH public key: /home/freek/.ssh/id_rsa.pub
I1104 01:07:14.819645   18019 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet eu-west-1a
I1104 01:07:14.819724   18019 subnets.go:183] Assigned CIDR 172.20.64.0/19 to subnet eu-west-1b
I1104 01:07:14.819749   18019 subnets.go:183] Assigned CIDR 172.20.96.0/19 to subnet eu-west-1c
I1104 01:07:18.382928   18019 apply_cluster.go:420] Gossip DNS: skipping DNS validation
I1104 01:07:19.105633   18019 executor.go:91] Tasks: 0 done / 71 total; 32 can run
I1104 01:07:22.775324   18019 vfs_castore.go:422] Issuing new certificate: "kubelet"
I1104 01:07:23.197646   18019 vfs_castore.go:422] Issuing new certificate: "kubecfg"
I1104 01:07:24.088259   18019 vfs_castore.go:422] Issuing new certificate: "kops"
I1104 01:07:24.609119   18019 vfs_castore.go:422] Issuing new certificate: "kube-controller-manager"
I1104 01:07:26.017551   18019 vfs_castore.go:422] Issuing new certificate: "kube-proxy"
I1104 01:07:27.396429   18019 vfs_castore.go:422] Issuing new certificate: "kube-scheduler"
I1104 01:07:29.259626   18019 executor.go:91] Tasks: 32 done / 71 total; 15 can run
I1104 01:07:30.152678   18019 executor.go:91] Tasks: 47 done / 71 total; 20 can run
I1104 01:07:31.194011   18019 launchconfiguration.go:327] waiting for IAM instance profile "masters.example.cluster.k8s.local" to be ready
I1104 01:07:31.264360   18019 launchconfiguration.go:327] waiting for IAM instance profile "nodes.example.cluster.k8s.local" to be ready
I1104 01:07:41.599136   18019 executor.go:91] Tasks: 67 done / 71 total; 3 can run
I1104 01:07:45.032003   18019 vfs_castore.go:422] Issuing new certificate: "master"
I1104 01:07:45.639991   18019 executor.go:91] Tasks: 70 done / 71 total; 1 can run
I1104 01:07:45.942514   18019 executor.go:91] Tasks: 71 done / 71 total; 0 can run
I1104 01:07:46.676225   18019 update_cluster.go:247] Exporting kubecfg for cluster
Kops has set your kubectl context to example.cluster.k8s.local

Cluster is starting.  It should be ready in a few minutes.

[...]

freek@freek-vb-u1604:~/freek/AwsWorkshop$ kops validate cluster
Using cluster from kubectl context: example.cluster.k8s.local

Validating cluster example.cluster.k8s.local

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-eu-west-1a	Master	m3.medium	1	1	eu-west-1a
nodes			Node	t2.medium	2	2	eu-west-1a,eu-west-1b,eu-west-1c

NODE STATUS
NAME						ROLE	READY
ip-172-20-52-214.eu-west-1.compute.internal	master	True
ip-172-20-90-48.eu-west-1.compute.internal	node	True
ip-172-20-99-53.eu-west-1.compute.internal	node	True

Your cluster example.cluster.k8s.local is ready
freek@freek-vb-u1604:~/freek/AwsWorkshop$ 
freek@freek-vb-u1604:~/freek/AwsWorkshop$ kubectl get nodes --show-labels
NAME                                          STATUS    ROLES     AGE       VERSION   LABELS
ip-172-20-52-214.eu-west-1.compute.internal   Ready     master    3m        v1.7.4    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m3.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1a,kubernetes.io/hostname=ip-172-20-52-214.eu-west-1.compute.internal,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-172-20-90-48.eu-west-1.compute.internal    Ready     node      1m        v1.7.4    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1b,kubernetes.io/hostname=ip-172-20-90-48.eu-west-1.compute.internal,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-20-99-53.eu-west-1.compute.internal    Ready     node      1m        v1.7.4    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1c,kubernetes.io/hostname=ip-172-20-99-53.eu-west-1.compute.internal,kubernetes.io/role=node,node-role.kubernetes.io/node=

**Comment by wombat** [comment]
@FreekDB great! Glad it worked :)
