### ISSUE TITLE
use brew for installing awscli

### ISSUE THREAD

**Issue by tubbynl** [arun-gupta/kubernetes-aws-workshop#176]
when going into the kops part; for macOS brew is used.

if you are already using that maybe python and awscli can also be installed like that (brew install awscli), it would ease the installing and make it less error prone, if you want i can create a pull request for updating the docs

**Comment by arun-gupta** [comment]
Sounds like a good idea.

Can you update instructions to install `brew` on a fresh mac? This should include installing python and pip as well.

**Comment by tubbynl** [comment]
yes; those can also be installed via brew
