### ISSUE TITLE
Package application as Helm Chart

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#18]
Explain how an application consisting of multiple k8s resources can be packaged as Helm Chart.

Helm: https://github.com/kubernetes/helm
Charts: https://github.com/kubernetes/charts

**Comment by omarlari** [comment]
assign to @omarlari

**Comment by arun-gupta** [comment]
Added https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/helm
