### ISSUE TITLE
Missing export

### ISSUE THREAD

**Issue by cmanikandan** [arun-gupta/kubernetes-aws-workshop#187]
Under https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/prereqs.adoc#aws-availability-zones - should'nt this be?
_export AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"_

**Comment by arun-gupta** [comment]
Without `export` works on my machine. What O/S are you using?

**Comment by cmanikandan** [comment]
Using Mac, its just that it mentions that you will be using across the labs by different scripts and commands, hence felt exporting is a safer bet ..

**Comment by arun-gupta** [comment]
Would that work on Windows as well?

**Comment by cmanikandan** [comment]
No, just Mac and Linux ..

**Comment by arun-gupta** [comment]
That might be ok since kops only works on Mac and Linux anyway. And even on Windows, we ask to enable Linux subsystem.

Fix coming
