### ISSUE TITLE
developer-concepts / create a pod section

### ISSUE THREAD

**Issue by rpcme** [arun-gupta/kubernetes-aws-workshop#197]
It displays configuration, and says to run the command line, but doesn't literally tell you to create that file.

**Comment by rpcme** [comment]
same issue with "create a deployment" section

**Comment by arun-gupta** [comment]
@rpcme all those files exist in `templates` directory. This is also mentioned in https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/developer-concepts#pre-requisites.

Do you think its not clear?

**Comment by rpcme** [comment]
it's not clear.  before every configuration block, the file location should be pointed out.

**Comment by riywo** [comment]
I think adding `cd developer-concepts/` command in the pre-requisites section makes it clearer.

**Comment by arun-gupta** [comment]
All the chapters explicitly mention the director where configuration files are available. Do you still think `cd <directory>` would be useful?
