### ISSUE TITLE
Nginx Ingress Controller Missing service-l7.yaml

### ISSUE THREAD

**Issue by jasonumiker** [arun-gupta/kubernetes-aws-workshop#199]
I believe that you intended for this file to be in the distrubution to be edited with the ECM ARN https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-l7.yaml

**Comment by arun-gupta** [comment]
Are you saying that the instructions to edit the file are not available in the instructions?

**Comment by jasonumiker** [comment]
There is no copy of or link to the file - I had to go find the ingress-nginx project and get the file manually from there. 

It would also be good to have an example of exposing a service via this in the section as well.

**Comment by arun-gupta** [comment]
The `ingress-controllers` section was added 3 days ago and is not ready for full testing yet. Can you update the instructions as you are moving along and send a PR?

**Comment by jasonumiker** [comment]
Done
