### ISSUE TITLE
app-pod manifest does not include a label

### ISSUE THREAD

**Issue by jicowan** [arun-gupta/kubernetes-aws-workshop#205]
The app-pod.yaml manifest does not include a label.  This prevents you from creating a service later.  The app-pod manifest needs to be updated with a label, e.g. 

metadata.labels.name = app-pod

This affects section, https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/config-secrets#consume-as-pod-environment-variables

**Comment by dalbhanj** [comment]
Closing as this issue is fixed in https://github.com/arun-gupta/kubernetes-aws-workshop/pull/212
