### ISSUE TITLE
cronjobs get pods command does nothing

### ISSUE THREAD

**Issue by rnzsgh** [arun-gupta/kubernetes-aws-workshop#206]
In the cronjob job specification, I do not see where the label app=hello-cronpod is set.

The result is that this command does not return anything, even though the cronjob is actually running.

kubectl get -w pods -l app=hello-cronpod

https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/developer-concepts#create-cron-job

**Comment by rnzsgh** [comment]
The template file in the directory is correct. The problem is in the documentation in in the readme file does not reflect what is in the file.

**Comment by wombat** [comment]
It has been resolved with #212
