### ISSUE TITLE
typo in curl commands

### ISSUE THREAD

**Issue by jicowan** [arun-gupta/kubernetes-aws-workshop#208]
There is a typo in the curl commands at the end of this lab, https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/microservices#access-application

curl
ac6a20167c0ca11e7b9a50e129c83717.us-east-1.elb.amazonaws.com*0*?greet=ho
The *0* should be removed.

**Comment by wombat** [comment]
@jicowan Where have you found this typo? I can´t find the command you are mentioning

**Comment by arun-gupta** [comment]
Fixed in https://github.com/arun-gupta/kubernetes-aws-workshop/pull/204
