### ISSUE TITLE
Grafana dashboards are empty

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#220]
Grafana dashboards at https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/cluster-monitoring#grafana-dashboard-1 are not showing any data from the nodes and pods.

This is a follow up from https://github.com/arun-gupta/kubernetes-aws-workshop/issues/186.

**Comment by wombat** [comment]
Should be fixed by #222
