### ISSUE TITLE
A small request - Please add a warning to the homepage

### ISSUE THREAD

**Issue by jasonmacdonald** [arun-gupta/kubernetes-aws-workshop#226]
First, thank-you for the great tutorial/workshop you have put together here. It is immensely helpful to those of us trying to explore running K8 on AWS.

I do, however, believe it would be very beneficial to add a warning, either on the homepage or even throughout the sections, that many of the EC2 instances spun up during this workshop do not qualify for the free tier on AWS. They will get billed for usage while running through the workshop. A repeated footer section reminding people to destroy their clusters after each section would also be very helpful, in case people skip over this initial warning. 

In hindsight, I realize this (cost) is probably obvious to those writing the workshop, but I foolishly started going through the workshop without paying close enough attention to what instance sizes Kops was using and got a bill the next day. Granted, it was not for a lot - only a couple dollars as I was diligent about tearing things down quickly after completing a section - but I still received a bill despite my diligence. I believe making people aware of this fact up front will help ensure no one is surprised, especially those not familiar with how AWS pricing works. 

I would hate for people to get surprised by a bill like I did, or worse yet forgetting to tear down the cluster after each section and getting a much larger bill, as it may give people an (undeserved) bad impression of both the workshop and AWS.

Again, thank-you very much for all your hard work and I truly do appreciate the effort you have put into this!

**Comment by dalbhanj** [comment]
Hi Jason, I think we have someone working on this issue here https://github.com/arun-gupta/kubernetes-aws-workshop/issues/88

But you are correct, we should at least provide a warning as the work is being done to cover it. Do you think if it makes sense to add this at https://github.com/arun-gupta/kubernetes-aws-workshop
or in https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/prereqs.adoc ?

**Comment by dalbhanj** [comment]
this is resolved

**Comment by jasonmacdonald** [comment]
@dalbhanj Thanks for the update. Sorry for the late reply.
