### ISSUE TITLE
Adding a note to gossip-based cluster creation on London AWS Region

### ISSUE THREAD

**Issue by andresguisado** [arun-gupta/kubernetes-aws-workshop#227]
Hi, 

Could you please add at `kubernetes-aws-workshop/cluster-install/readme.adoc` file the following note when you're executing `kops create cluster` as gossip-based?

> NOTE: If you're using London region(eu-west-2) you should add `--cloud aws` as kops is not identifying that eu-west-2 indicates AWS.Further info https://github.com/kubernetes/kops/issues/1267

if not, it is failing as follows:

> unable to infer CloudProvider from Zones (is there a typo in --zones?)

Thanks

**Comment by arun-gupta** [comment]
@andresguisado confirming this as an issue. Can you send a PR with this change?
