### ISSUE TITLE
Incorrect terminology in kubernetes-aws-workshop/cluster-install/readme.adoc

### ISSUE THREAD

**Issue by seangreathouse** [arun-gupta/kubernetes-aws-workshop#234]
"requires a top-level domain or a subdomain"
Customers would need their own domain, not 'top level domain' 
A TLD is .com or .net, not foo.com or foo.net
Small thing, I know....
Great project!

**Comment by arun-gupta** [comment]
Fair point. Do you want to send a PR with the suggested wording?
