### ISSUE TITLE
Pod Auto-scaling

### ISSUE THREAD

**Issue by boardthatpowder** [arun-gupta/kubernetes-aws-workshop#28]
Demonstrate auto-scaling of pods via Horizontal Pod Scaling.

**Comment by TrevorRobertsJr** [comment]
assign to @TrevorRobertsJr

**Comment by TrevorRobertsJr** [comment]
Base horizontal pod autoscaling functionality is described, and an example is documented. Future iterations of this content will feature custom metrics autoscaling when the feature is released.

**Comment by arun-gupta** [comment]
@TrevorRobertsJr can you link the PR?
