### ISSUE TITLE
Secrets with Hashicorp Vault

### ISSUE THREAD

**Issue by wombat** [arun-gupta/kubernetes-aws-workshop#3]
Add a separate section for ops showing how secrets can be securely stored e.g. in Hashicorp Vault and provided as K8s secrets to a dev

**Comment by arun-gupta** [comment]
Refactoring with #15

**Comment by arun-gupta** [comment]
Fixed by https://github.com/arun-gupta/kubernetes-aws-workshop/commit/bfb86d03e65bbf0b6615a8b9c61bf137b76b9f69
