### ISSUE TITLE
Install cluster using kops

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#5]
Add instructions on how to setup a k8s cluster using `kops`. Base blog: https://aws.amazon.com/blogs/compute/kubernetes-clusters-aws-kops/

Here are different use cases:

- Gossip-based cluster for test/dev (more details at http://blog.arungupta.me/gossip-kubernetes-aws-kops/)
- Single region, multi-AZ master and multi-AZ workers
- With public VPC and private VPC
- `--networking` with `calico` and `flannel`
- `--target` with `direct` (default) and `terraform`

**Comment by omarlari** [comment]
assign to @omarlari

**Comment by dalbhanj** [comment]
talked to @omarlari, please assign this to me (@dalbhanj) as I have most of the steps written for this already
