### ISSUE TITLE
Instance Groups

### ISSUE THREAD

**Issue by christopherhein** [arun-gupta/kubernetes-aws-workshop#57]
How to use instance groups with `kops` to add other instance types to your k8s cluster. https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md

**Comment by chrislovecnm** [comment]
And also to make ig per az. Lots of reasons to not span az with ig.

Autoscaler
EBS volumes
Etc

**Comment by MCLDG** [comment]
PR #238 mostly resolves this issue, with the exception of an ig per az. I'll leave the issue open for now.

**Comment by MCLDG** [comment]
PR #238 updated with IG per AZ added to resolve this issue.  Issue can be closed.
