### ISSUE TITLE
Rolling update of an application

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#7]
Show rolling update of an application, basic sample at: https://github.com/arun-gupta/kubernetes-java-sample/tree/master/rolling-update

**Comment by arun-gupta** [comment]
Similar to #2

**Comment by w0mbat** [comment]
@arun-gupta @CloudyMind Do you think this is already sufficiently shown by PR #26 or do we want to go into more detail?

**Comment by arun-gupta** [comment]
@w0mbat PR #26 covers it well
