### ISSUE TITLE
Grafana dashboard with Prometheus is not working

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#80]
Grafana dashboard with Prometheus shows the following screen:

<img width="606" alt="screen shot 2017-10-19 at 12 51 48 pm" src="https://user-images.githubusercontent.com/113947/31791062-5037352e-b4cc-11e7-9900-9a2431721f40.png">

CC: @omarlari

**Comment by wombat** [comment]
@arun-gupta I just executed the Heapster installation instructions in `cluster-monitoring`, did a `kubectl proxy` and was able to access the grafana dashboard as describe from `http://localhost:8001/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy/?orgId=1`.
