### ISSUE TITLE
Creating a cluster with VPC endpoint does not respond

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/kubernetes-aws-workshop#85]
Followed the instructions at https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/cluster-install#multi-master-multi-node-multi-az-dns-based-cluster-with-private-vpc-hosted-zone

Validating the cluster gives the following error:

```
$ kops validate cluster --name=cluster.k8s-aws.internal
Validating cluster cluster.k8s-aws.internal


cannot get nodes for "cluster.k8s-aws.internal": Get https://api.cluster.k8s-aws.internal/api/v1/nodes: dial tcp: lookup api.cluster.k8s-aws.internal: no such host
```

**Comment by MCLDG** [comment]
I can't see how this would work. The R53 setup is associating the domain api.cluster.k8s-aws.internal with the IP address of one of the master nodes, but since the domain is private it can't be referenced externally.  I suspect you'd need to SSH into one of the servers to be able to access the cluster. Let me look into it further.

**Comment by arun-gupta** [comment]
@MCLDG Here are two questions that I don't understand:

- What is the need to use a private VPC?
- if private VPC will work with gossip-based cluster or DNS-based cluster?

I think that'll help define and categorize the content accordingly.

**Comment by MCLDG** [comment]
OK, seems this is a known issue. See here: [https://github.com/kubernetes/kops/issues/2032]. The following workarounds exist:

1. - 1. - Use VPN to VPC; you can access the private API endpoint from inside the VPC.
2. - 2. - Use a public and private route53 zone with the same domain. In the public zone, create an A record to the API server; the A record should link to the ELB. Remove the API server from the private hosted zone. This is explained here under the 'Edit the cluster' section: http://kubecloud.io/setup-ha-k8s-kops/

Let's remove this section from the workshop. We can refer to the documentation if people are interested, but I'd suggest we remove details on how to do it.

**Comment by arun-gupta** [comment]
@MCLDG sounds good. can you send a PR to update `cluster-install`?

**Comment by arun-gupta** [comment]
Took care of this as part of another update
