### ISSUE TITLE
Explain billing expectations

### ISSUE THREAD

**Issue by QuinnyPig** [arun-gupta/kubernetes-aws-workshop#88]
"What is this going to cost me" is probably a question that should be addressed up front. Not everyone's going to have an account in the free tier, and people are scared of AWS billing surprises!

**Comment by arun-gupta** [comment]
This would be a good section to be added in https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/cluster-install.

@QuinnyPig Do you want to take a shot at it?

**Comment by QuinnyPig** [comment]
Sure. I'll validate this before PRing, but back-of-the-envelope numbers for the resources on that page come out to around $1 an hour, plus 50¢ for the Route53 zone.

Or "hundreds of dollars on the next bill if you forget that this is there," so definitely worth calling that out up front. Will PR as I go through it back on a non-conference machine later in the week.

**Comment by dalbhanj** [comment]
this is resolved
