### ISSUE TITLE
Region Confusion

### ISSUE THREAD

**Issue by QuinnyPig** [arun-gupta/kubernetes-aws-workshop#89]
Is eu-central-1 the "blessed region" for this workshop at re:Invent? If so, I'll go through and change all the code snippets to reflect that in a PR; just want to make sure that the latency from LAS is going to be considered acceptable.

**Comment by arun-gupta** [comment]
`eu-central-1` is the "blessed region" for this workshop at re:Invent. Just changing the region may not be sufficient. It would also mean testing the exact command as well, as requires AZs to be specified in some cases.

**Comment by QuinnyPig** [comment]
Perfect. That's why I'm asking now, before I dive into the workshop myself. I'll modify the regional statements I encounter as I go.
